### ISSUE TITLE
RuntimeError: The shape of the mask ... does not match

### ISSUE THREAD

**Issue by witignite** [witignite/ssd_pytorch#1]
**Branch:** `master`
Run a quick demo on COCO dataset:
```bash
python train.py --dataset COCO --dataset_root /home/w/P/DataSet/COCO --batch_size 1 --cuda False --lr 1e-4
```
Error:
```bash
...
Namespace(basenet='vgg16_reducedfc.pth', batch_size=1, cuda=False, dataset='COCO', dataset_root='/home/w/P/DataSet/COCO', gamma=0.1, lr=0.001, momentum=0.9, num_workers=4, resume=None, save_folder='weights/', start_iter=0, visdom=False, weight_decay=0.0005)
train.py:172: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  targets = [Variable(ann, volatile=True) for ann in targets]
/home/w/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train()
  File "train.py", line 178, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/w/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/w/P/ssd_pytorch/layers/modules/multibox_loss.py", line 97, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
IndexError: The shape of the mask [1, 8732] at index 0does not match the shape of the indexed tensor [8732, 1] at index 0
```

**Comment by witignite** [comment]
1. Switch two lines 97 and 98 in `multibox_loss.py`:
    ```python3
    loss_c = loss_c.view(num, -1)
    loss_c[pos] = 0  # filter out pos boxes for now
    ```
2. Change line 114 in `multibox_loss.py` to:
    ```python3
    N = num_pos.data.sum().double()
    loss_l = loss_l.double()
    loss_c = loss_c.double()
    ```
3. Change every instance in `train.py` from `loss_x.data[0]` to `loss_x.item()`
